---
driver:
  name: docker

platforms:
  - name: instance_ubuntu_22.04
    image: ubuntu:22.04
    pre_build_image: false
    privileged: true
    build:
      context: .

  - name: instance_debian_13
    image: debian:13
    pre_build_image: false
    privileged: true
    build:
      context: .

provisioner:
  name: ansible
  config_options:
    defaults:
      collections_path: collections
      roles_path: ../..
  playbooks:
    converge: playbook.yml
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
    ANSIBLE_COLLECTIONS_PATH: ../../collections
    ANSIBLE_ROLES_PATH: ../..

verifier:
  name: ansible

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
