---
- name: Verify user creation
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if user exists
      ansible.builtin.command: id mbr
      register: user_check
      failed_when: user_check.rc != 0
      changed_when: false

    - name: Check user groups
      ansible.builtin.assert:
        that:
          - "'sudo' in user_check.stdout"
      when: ansible_facts.os_family == 'Debian'

    - name: Check user groups
      ansible.builtin.assert:
        that:
          - "'wheel' in user_check.stdout"
      when: ansible_facts.os_family == 'RedHat'

    - name: Verify .ssh directory permissions
      ansible.builtin.stat:
        path: /home/mbr/.ssh
      register: ssh_dir

    - name: Assert .ssh directory exists
      ansible.builtin.assert:
        that:
          - ssh_dir.stat.exists
          - ssh_dir.stat.mode == '0700'

    - name: Verify authorized keys
      ansible.builtin.command: cat /home/mbr/.ssh/authorized_keys
      register: authorized_keys
      changed_when: false

    - name: Assert authorized keys file contains data
      ansible.builtin.assert:
        that:
          - authorized_keys.stdout is not none

- name: Verify base packages configuration
  hosts: all
  gather_facts: true
  tasks:
    - name: Verify base packages configuration
      ansible.builtin.include_tasks: verify_packages_{{ ansible_facts.os_family }}.yml

- name: Verify base resolv.conf configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if resolv.conf exists
      ansible.builtin.stat:
        path: /etc/resolv.conf.check
      register: resolv_conf

    - name: Fail if resolv.conf is missing
      ansible.builtin.fail:
        msg: "File /etc/resolv.conf.check is missing!"
      when: not resolv_conf.stat.exists

    - name: Read resolv.conf
      ansible.builtin.command: cat /etc/resolv.conf.check
      register: resolv_conf_content
      changed_when: false

    - name: Validate nameservers
      ansible.builtin.assert:
        that:
          - "'nameserver 1.1.1.1' in resolv_conf_content.stdout"
          - "'nameserver 8.8.8.8' in resolv_conf_content.stdout"
          - "'search perfectcircle.tech' in resolv_conf_content.stdout"
          - "'options timeout:2 attempts:3' in resolv_conf_content.stdout"
